### ISSUE TITLE
Stable ordering of gates in index page

### ISSUE THREAD

**Issue by LostKobrakai** [tompave/fun_with_flags_ui#14]
It would be nice if listed gates for flags are ordered the same for each row, which makes is quicker to scan.

**Comment by tompave** [comment]
Yup, I'd agree. Thank you for pointing it out. I'd be happy to accept a PR for this.

At the moment the order comes from whatever is returned by `FunWithFlags.all_flags/0`, and it depends on persistence store.

I think that it would be convenient to also sort the gates here: https://github.com/tompave/fun_with_flags_ui/blob/8dc2ff3bca2c0793d34172a9177758180c912d87/lib/fun_with_flags/ui/router.ex#L74

**Comment by tompave** [comment]
Closed with https://github.com/tompave/fun_with_flags_ui/pull/16

Thanks! 👍
