### ISSUE TITLE
Percentage gates display as scientific notation

### ISSUE THREAD

**Issue by a-kinder** [tompave/fun_with_flags_ui#18]
Percentage input is displaying as scientific notation on new flag page.
![image](https://user-images.githubusercontent.com/8903097/94963582-c207d780-04ce-11eb-81c8-4e37fb3812f2.png)

**Comment by tompave** [comment]
Hello, thank you for reporting the issue.

What's the value stored in the DB? Can you inspect it with `iex -S mix`?

**Comment by a-kinder** [comment]
![image](https://user-images.githubusercontent.com/8903097/95001262-a3711180-059e-11eb-952f-c52d6263f4bc.png)
It saves it with scientific notation as well. I've run into this before, it has something to do with floats not being exact, 1.0 is actually 1.000000001 or something and so scientific notation is the "shortest" way to display a float in an input.

**Comment by tompave** [comment]
Ok. I was wondering if the exponential representation happened in Elixir or in the browser (could have been some odd browser behaviour).

> It saves it with scientific notation as well.

I don't think it has anything to do with how the floats are saved. What Elixir stores in memory is a value, and what changes is how it gets represented to the user (in the terminal, or when rendering an HTML page).

With `1.0e-9`, I suspect that you originally entered `0.000000001`. That seems to be the case:

```elixir
0.000000001 |> Float.to_string()
"1.0e-9"
```

> it has something to do with floats not being exact, 1.0 is actually 1.000000001 or something and so scientific notation is the "shortest" way to display a float in an input.

I don't think that floating-point arithmetic has anything to do with this:

```elixir
1.0 |> Float.to_string()
"1.0"
```

> and so scientific notation is the "shortest" way to display a float in an input.

This is correct only in the sense that the string `"1.0e-9"` is shorter and arguably easier to read than the string `"0.000000001"`, so Elixir renders uses that format to convert that float value to string. Other languages behave in exactly the same way. (Try `(0.000000001).toString();` in your browser's JS console)

**Comment by tompave** [comment]
To resolve your problem, I would say that `0.000000001` is a technically valid value, but in practical terms it's equivalent to zero.

For % gates, `1.0 == 100%` and `0.01 == 1%`.
So, `0.000000001 == 0.0000001%`. That's not too different from `0%`.

**Comment by a-kinder** [comment]
Ah ok, sorry my confusion was I didn't realize your step value was so tiny. I swear I was having issues with typing in a decimal but apparently I imagined that. Thanks for the response.
