### ISSUE TITLE
How to select DB to read flags

### ISSUE THREAD

**Issue by Fl4m3Ph03n1x** [tompave/fun_with_flags_ui#35]
Background
--------

We are using this UI to check the flags we have on redis. Since Redis has several DBs one can choose from, this raises a problem - we need to tell the UI which Redis DB to use. 

Problem
-----

After reading the docs, I couldn't find any option to do that. By default, the UI will always read from Redis DB 1, which is not where our flags are. 

Is there a way to tell the UI which Redis DB to use?

**Comment by tompave** [comment]
Hey there, thank you for using the library.

FWF.UI is just the presentation layer, and in fact it doesn't provide any config option, aside from the way you plug it into your Phoenix or Plug routers.

The persistence layer is provided by the underlying library, [fun_with_flags](https://hex.pm/packages/fun_with_flags). It supports [a number of config options](https://github.com/tompave/fun_with_flags#configuration), including the Redis DB number. You can configure it with this:

```elixir
config :fun_with_flags, :redis, database: 5
```

**Comment by Fl4m3Ph03n1x** [comment]
This was not evident to me. Thanks!
