### ISSUE TITLE
Update to fun_with_flags v1.12.0 - for Elixir 1.17 and 1.16 support

### ISSUE THREAD

**Issue by rob-vetspire** [tompave/fun_with_flags_ui#41]
A polite request to update `fun_with_flags_ui` to use the very recently released [fun_with_flags v1.12.0](https://github.com/tompave/fun_with_flags/blob/master/CHANGELOG.md#v1120) - for Elixir 1.17 and 1.16 support.

**Comment by tompave** [comment]
Hey there, thank you for raising it. This has now been done here: https://github.com/tompave/fun_with_flags_ui/pull/42.

I believe that, even without this explicit update, `fwf_ui 1.0` should have worked with both `fwf 1.12` and latest Elixir and OTP, though. Have you encountered any issue you'd like to call out?
